/*
 * Wager service APIs
 *
 * APIs for a wager system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controllers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ListWagersGet - 
func ListWagersGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
