/*
 * Wager service APIs
 *
 * APIs for a wager system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wager
// CreateWagerRequest struct for CreateWagerRequest
type CreateWagerRequest struct {
	TotalWagerValue int32 `json:"total_wager_value"`
	Odds int32 `json:"odds"`
	SellingPercentage int32 `json:"selling_percentage"`
	SellingPrice float32 `json:"selling_price"`
}
